name: smsflutter
description: A new Flutter project.

publish_to: 'none' 



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: ^0.16.1


  cupertino_icons: ^1.0.0
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  provider: ^3.1.0
  email_validator: '^1.0.5'
  flutter_spinkit: "^4.1.2"
  shared_preferences: any
  charts_flutter: any
  video_player:

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:

  generate: true
  uses-material-design: true

 
